name: CI
on: [push, pull_request]

jobs:
  install:
    name: "Test install: (${{ matrix.python-version }}, ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
      - name: Install
        run: pip install -r requirements.txt